CREATE TABLE pm (
 _id INTEGER  PRIMARY KEY NOT NULL,
 name TEXT NOT NULL,
 health INTEGER,
 type TEXT,
 stage INTEGER,
 retreat INTEGER,
 year TEXT);
CREATE TABLE energy (
 _id INTEGER  PRIMARY KEY NOT NULL,
 type TEXT NOT NULL,
 year TEXT
 );